token = "bot_token"
topgg_token = ""
owners = [ 141231597155385344, ]  # The first should always be the developer
dm_uncaught_errors = false
default_prefix = "!"  # The prefix for the bot's commands
guild_id = 1  # The ID of the main/support guild
event_webhook_url = ""

# Data that's copied directly over to a command without processing
[command_data]
    guild_invite = ""
    github_link = ""
    donate_link = ""
    invite_command_permissions = [ "read_messages", ]
    echo_command_enabled = true
    stats_command_enabled = true
    vote_command_enabled = false

# This data is passed directly over to asyncpg
[database]
    user = "database_username"
    password = "database_password"
    database = "database_name"
    host = "127.0.0.1"
    port = 5432
    enabled = false

# This data is passed directly over to aioredis
[redis]
    host = "127.0.0.1"
    port = 6379
    db = 0
    enabled = false

# The data that gets shoves into custom context for the embed
[embed]
    enabled = false  # whether or not to embed messages by default
    content = ""  # default content to be added to the embed message
    colour = 0  # a specific colour for the embed - 0 means random
    [embed.author]
        enabled = false
        name = "{ctx.bot.user}"
        url = ""  # the url added to the author
    [[embed.footer]]  # an array of possible footers
        text = "Add the bot to your server! ({ctx.clean_prefix}invite)"  # text to appear in the footer
        amount = 1  # the amount of times this particular text is added to the pool

# What the bot is playing
[presence]
    activity_type = "playing"  # Should be one of 'playing', 'listening', 'watching'
    text = "Game playing text"
    status = "online"  # Should be one of 'online', 'invisible', 'idle', 'dnd'

# Used to generate the invite link - client ID only necessary for webserver
[oauth]
    client_id = ""
    client_secret = ""

# This is where you can set up all of your analytics to be sent to GA
[google_analytics]
    tracking_id = ""  # Tracking ID for your GA instance
    app_name = ""  # The name of your bot - what you want GA to name this traffic source
    document_host = ""  # The (possibly fake) URL you want to tell GA this website is
